### ISSUE TITLE
Preserve case-sensitive path for `--data`

### ISSUE THREAD

**Issue by lnmx** [samoht/mirage-seal#18]
From mirage/mirage#434:

The `--data` directory is passed to config.ml as the `SEAL_DATA` env var.  When reading this value with `get`, it is coerced to lowercase [1], leading to the "directory not found" error.  

This would affect `--keys` as well.

[1] https://github.com/mirage/mirage-seal/blob/116730293f4cdc7db85599a0b0df53f935a474d5/static/config.ml#L13

**Comment by samoht** [comment]
0.4.2 is released in opam: https://github.com/ocaml/opam-repository/pull/4549
