### ISSUE TITLE
Add a `--no-https` option to serve static HTTP contents.

### ISSUE THREAD

**Issue by samoht** [samoht/mirage-seal#6]

**Comment by samoht** [comment]
I've implemented something similar. To serve contents over http:

```
mirage-seal -d <dir>`
```

to serve contents over https:

```
mirage-seal -d <dir> -k <keys>
```

**Comment by hannesm** [comment]
imho this is highly non-intuitive (and error-prone if a user forgets to pass `-k`), and a user should rather specify `--no-tls` explicitly

**Comment by samoht** [comment]
agreed, fixing this (this was a first cut to see how to do it)
